---
- name: Add SSH key to specific user
  ansible.posix.authorized_key:
    user: "{{ user }}"
    key: "{{ lookup('file', 'files/ssh/id_rsa.pub') }}"
  tags:
    - ssh
    - ssh_key_append
  when: ssh_access is defined and ssh_access == "present"
- name: Remove SSH key from specific user
  ansible.posix.authorized_key:
    user: "{{ user }}"
    key: "{{ lookup('file', 'files/ssh/id_rsa.pub') }}"
    state: absent
  tags:
    - ssh
    - ssh_key_delete
  when: ssh_access is defined and ssh_access == "absent"