- hosts: vms
  become: true
  user: vagrant
  vars:
    nginx_root_dir: /var/static/sites
    nginx_port: 80
  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
      tags:
        - nginx
        - install
    - name: copy nginx config
      template:
        src: files/nginx.conf
        dest: /etc/nginx/nginx.conf
      notify: reload nginx
      tags:
        - nginx
        - config
        - install
    - name: create nginx root dir
      file:
        path: "{{nginx_root_dir}}"
        state: directory
        owner: www-data
        group: www-data
        mode: 0755
      tags:
        - nginx
        - config
        - install
    - name: add html files to {{nginx_root_dir}}
      template:
        src: files/index.html
        dest: "{{nginx_root_dir}}/index.html"
        group: www-data
        owner: www-data
      tags:
        - nginx
        - html
        - install
    - name: remove nginx
      apt:
        name: nginx
        state: absent
      tags:
        - nginx
        - remove
    - name: remove html files
      shell: "rm -rf {{nginx_root_dir}}/*"
      tags:
        - nginx
        - html
        - remove
    - name: purge all nginx packets
      command: apt-get -y purge nginx*
      tags:
        - nginx
        - remove
    - name: autoremove unused packets
      apt:
        autoremove: yes
      tags:
        - nginx
        - remove
  handlers:
    - name: reload nginx
      service:
        name: nginx
        state: reloaded
      tags:
        - nginx
        - config